<b>Question 1</b>

In [19]:
import numpy as np
np.__version__

'1.19.2'

In [89]:
import pandas as pd
df = pd.read_csv("data.csv")
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

<b>Question 2</b>

In [21]:
np.max(df.count())
# and hence there are 11914 records. 

11914

<b>Question 3</b>

In [42]:
df.groupby(['Make'])['Model'].count().sort_values(ascending=False)
# and hence the answer is Chevrolet, Ford, Volkswagen

Make
Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
McLaren             5
Alfa Romeo          5
Bugat

<b>Question 4</b>

In [49]:
len(df[df['Make'] == 'Audi']['Model'].unique())
# 34 unique Audi car models

34

<b>Question 5</b>

In [56]:
df.isnull().sum()
# 5 columns with missing values: Engine Fuel Type, Engine HP, Engine Cylinders, Number of Doors, Market Category

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

<b>Question 6</b>

In [77]:
df['Engine Cylinders'].median()

6.0

In [92]:
temp = df['Engine Cylinders'].mode()
print(temp)

0    4.0
dtype: float64


In [91]:
df['Engine Cylinders'].fillna(temp, inplace=True)
df['Engine Cylinders'].median()
# No, it hasn't changed

6.0

<b>Question 7</b>

In [112]:
X = np.array(df[df['Make'] == 'Lotus'][['Engine HP', 'Engine Cylinders']].drop_duplicates())
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [113]:
XTX = np.matmul(X.T ,X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [114]:
invXTX = np.linalg.inv(XTX)
invXTX

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [116]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
w = np.matmul(np.matmul(invXTX, X.T), y)
w[0]
# the value is 4.5949

4.594944810094576